#SEA
sea_homepage:
    path:     /
    defaults: { _controller: SeaBundle:Default:index }
    methods: [GET]

sea_login:
      path:     /login
      defaults: { _controller: SeaBundle:Default:login }

sea_signin:
      path:     /signin
      defaults: { _controller: SeaBundle:Default:signin }

sea_associations:
    path:     /associations
    defaults: { _controller: SeaBundle:Association:list }
    methods: [GET]

sea_apropos:
      path:     /apropos
      defaults: { _controller: SeaBundle:Default:apropos }

sea_association:
    path:     /associations/{associationId}
    defaults: { _controller: SeaBundle:Association:details }
    methods: [GET]
    requirements:
        associationId: \d+

sea_research:
    path:     /research
    defaults: { _controller: SeaBundle:Association:research }
    methods: [POST]


