imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

assetic:
    assets:
        jquery_js: %kernel.root_dir%/../web/assetic/js/jquery.js
        bootstrap_validator_js: %kernel.root_dir%/../web/assetic/js/validator.js
        bootstrap_js: %kernel.root_dir%/../web/assetic/js/bootstrap.js
        bootstrap_css: %kernel.root_dir%/../web/assetic/css/bootstrap.css
        bootstrap_tags_js: %kernel.root_dir%/../web/assetic/js/bootstrap-tagsinput.js
        style_css: %kernel.root_dir%/../web/assetic/css/style.css
        bootstrap_tags_css: %kernel.root_dir%/../web/assetic/css/bootstrap-tagsinput.css
