# app/config/routing.yml
api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

sea:
    resource: "@SeaBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

