# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api_service:
        class: SeaBundle\Service\ApiService
        arguments: ["@router","@logger","%backend_url%", "%backend_proxy_host%"]

    association_service:
        class: SeaBundle\Service\AssociationService
        arguments: ['@api_service']

    category_service:
            class: SeaBundle\Service\CategoryService
            arguments: ['@api_service']