<?php

namespace SeaBundle\Repository;

/**
 * CityHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityHallRepository extends \Doctrine\ORM\EntityRepository
{
}
